#!/bin/bash

sudo dotnet restore ./DataAccessLayer/DataAccessLayer.csproj
sudo dotnet publish ./DataAccessLayer/DataAccessLayer.csproj -c Release -o ./DataAccessLayer/bin/Release

sudo dotnet restore ./SharedLibrary/SharedLibrary.csproj
sudo dotnet publish ./SharedLibrary/SharedLibrary.csproj -c Release -o ./SharedLibrary/bin/Release


sudo cp ./SharedLibrary/bin/Release/SharedLibrary.dll ./SentenceAPI/Assemblies/
sudo cp ./SharedLibrary/bin/Release/DataAccessLayer.dll ./DocumentsAPI/Assemblies/
sudo cp ./SharedLibrary/bin/Release/SharedLibrary.dll ./DocumentsAPI/Assemblies/
sudo cp ./SharedLibrary/bin/Release/DataAccessLayer.dll ./SentenceAPI/Assemblies/
