FROM mcr.microsoft.com/dotnet/core/sdk AS base
WORKDIR /sentenceAPIApp

EXPOSE 5000 5001 8080 8018

FROM mcr.microsoft.com/dotnet/core/sdk AS build
WORKDIR /src

COPY SentenceAPI.csproj SentenceAPI.csproj
RUN dotnet restore SentenceAPI.csproj

COPY . . 
RUN dotnet build SentenceAPI.csproj -c Release -o /sentenceAPIApp

FROM build AS publish 
RUN dotnet publish SentenceAPI.csproj -c Release -o /sentenceAPIApp

FROM base AS final
WORKDIR /sentenceAPIApp
COPY --from=publish /app .

ENTRYPOINT [ "dotnet", "SentenceAPI.dll"]